services:
  - type: web
    name: web-scraper
    env: docker
    docker:
      image: nyrew/web_scraper:updated
    envVars:
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: products
          property: connectionString